# Generated by Django 4.2.19 on 2025-02-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password_reset_created_at',
            new_name='password_reset_requested_at',
        ),
    ]
