# Generated by Django 4.2.19 on 2025-02-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_rename_password_reset_created_at_customuser_password_reset_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
